import { v4 as uuid } from 'uuid'
import {
  casualT1,
  casualT2,
  casualT3,
  casualT4,
  casualT5,
  casualT6,
  fitnessT1,
  fitnessT2,
  fitnessT3,
  fitnessT4,
  fitnessT5,
  fitnessT6,
  trackT1,
  trackT2,
  trackT3,
  trackT4,
  trackT5,
  trackT6,
  sportsT1,
  sportsT2,
  sportsT3,
  sportsT4,
  sportsT5,
  sportsT6,
} from '../../assets/assetsServer'
/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    isFeatured: false,
    title: 'Jordan Retro 5 SE',
    price: '17338',
    categoryName: 'casual',
    inWishlist: true,
    inCart: true,
    imgSrc: casualT1,
    rating: 4.5,
  },
  {
    _id: uuid(),
    isFeatured: true,
    title: 'Jordan Retro 6',
    price: '16512',
    categoryName: 'casual',
    inWishlist: false,
    inCart: false,
    imgSrc: casualT2,
    rating: 3.0,
  },
  {
    _id: uuid(),
    isFeatured: true,
    title: 'adidas Originals Forum',
    price: '13210',
    categoryName: 'casual',
    inWishlist: false,
    inCart: false,
    imgSrc: casualT3,
    rating: 3.0,
  },
  {
    _id: uuid(),
    isFeatured: true,
    title: 'New Balance 990v5',
    price: '15274',
    categoryName: 'casual',
    inWishlist: false,
    inCart: false,
    imgSrc: casualT4,
    rating: 3.0,
  },
  {
    _id: uuid(),
    isFeatured: true,
    title: 'Nike Air Uptempo',
    price: '13623',
    categoryName: 'casual',
    inWishlist: false,
    inCart: false,
    imgSrc: casualT5,
    rating: 3.0,
  },
  {
    _id: uuid(),
    isFeatured: true,
    title: 'Vans Sk8 Hi',
    price: '8256',
    categoryName: 'casual',
    inWishlist: false,
    inCart: false,
    imgSrc: casualT6,
    rating: 3.0,
  },
  {
    _id: uuid(),
    isFeatured: false,
    title: 'Adidas Ultraboost',
    price: '17599',
    categoryName: 'fitness',
    inWishlist: false,
    inCart: false,
    imgSrc: fitnessT1,
    rating: 4.5,
  },
  {
    _id: uuid(),
    isFeatured: true,
    title: 'Adidas 4D',
    price: '15799',
    categoryName: 'fitness',
    inWishlist: false,
    inCart: false,
    imgSrc: fitnessT2,
    rating: 3.0,
  },
  {
    _id: uuid(),
    isFeatured: false,
    title: 'New Balance Roav',
    price: '8999',
    categoryName: 'fitness',
    inWishlist: false,
    inCart: false,
    imgSrc: fitnessT3,
    rating: 5.0,
  },
  {
    _id: uuid(),
    isFeatured: false,
    title: 'On Cloud 5',
    price: '8999',
    categoryName: 'fitness',
    inWishlist: false,
    inCart: false,
    imgSrc: fitnessT4,
    rating: 5.0,
  },
  {
    _id: uuid(),
    isFeatured: false,
    title: 'HOKA Gaviota 4',
    price: '8999',
    categoryName: 'fitness',
    inWishlist: false,
    inCart: false,
    imgSrc: fitnessT5,
    rating: 5.0,
  },
  {
    _id: uuid(),
    isFeatured: false,
    title: 'ASICS GEL-Kinsei',
    price: '8999',
    categoryName: 'fitness',
    inWishlist: false,
    inCart: false,
    imgSrc: fitnessT6,
    rating: 5.0,
  },
  {
    _id: uuid(),
    isFeatured: true,
    title: 'Brroks Hyperion Max',
    price: '5999',
    categoryName: 'track',
    inWishlist: false,
    inCart: false,
    imgSrc: trackT1,
    rating: 3.5,
  },
  {
    _id: uuid(),
    isFeatured: false,
    title: 'HOKA Challenger ATR',
    price: '11559',
    categoryName: 'track',
    inWishlist: false,
    inCart: false,
    imgSrc: trackT2,
    rating: 4.5,
  },
  {
    _id: uuid(),
    isFeatured: false,
    title: 'Nike Tempo Next',
    price: '16512',
    categoryName: 'track',
    inWishlist: false,
    inCart: false,
    imgSrc: trackT3,
    rating: 4.5,
  },
  {
    _id: uuid(),
    isFeatured: false,
    title: 'Saucony Endorphin',
    price: '13210',
    categoryName: 'track',
    inWishlist: false,
    inCart: false,
    imgSrc: trackT4,
    rating: 4.5,
  },
  {
    _id: uuid(),
    isFeatured: false,
    title: 'ASICS Novablast 3',
    price: '11476',
    categoryName: 'track',
    inWishlist: false,
    inCart: false,
    imgSrc: trackT5,
    rating: 4.5,
  },
  {
    _id: uuid(),
    isFeatured: false,
    title: 'Under Armour Hovr Phantom',
    price: '11476',
    categoryName: 'track',
    inWishlist: false,
    inCart: false,
    imgSrc: trackT6,
    rating: 4.5,
  },
  {
    _id: uuid(),
    isFeatured: true,
    title: 'Nike Lebron XX',
    price: '5890',
    categoryName: 'sports',
    inWishlist: false,
    inCart: false,
    imgSrc: sportsT1,
    rating: 4,
  },
  {
    _id: uuid(),
    isFeatured: false,
    title: 'Nike Zoom G.T',
    price: '16512',
    categoryName: 'sports',
    inWishlist: false,
    inCart: false,
    imgSrc: sportsT2,
    rating: 3.5,
  },
  {
    _id: uuid(),
    isFeatured: false,
    title: 'New Balance Kawhi II',
    price: '13210',
    categoryName: 'sports',
    inWishlist: false,
    inCart: false,
    imgSrc: sportsT3,
    rating: 3.5,
  },
  {
    _id: uuid(),
    isFeatured: false,
    title: 'Under Armour Curry 9',
    price: '13210',
    categoryName: 'sports',
    inWishlist: false,
    inCart: false,
    imgSrc: sportsT4,
    rating: 3.5,
  },
  {
    _id: uuid(),
    isFeatured: false,
    title: 'New Balance TWO WXY',
    price: '13210',
    categoryName: 'sports',
    inWishlist: false,
    inCart: false,
    imgSrc: sportsT5,
    rating: 3.5,
  },
  {
    _id: uuid(),
    isFeatured: false,
    title: 'adidas Harden Vol 7',
    price: '13210',
    categoryName: 'sports',
    inWishlist: false,
    inCart: false,
    imgSrc: sportsT6,
    rating: 3.5,
  },
]
