import { v4 as uuid } from 'uuid'

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    isFeatured: false,
    title: 'Vans Old Skool',
    price: '5499',
    categoryName: 'casual',
    inWishlist: true,
    inCart: true,
    imgSrc: casualT1,
    rating: 4.5,
  },
  {
    _id: uuid(),
    isFeatured: true,
    title: 'Adidas Gazelle',
    price: '7799',
    categoryName: 'casual',
    inWishlist: false,
    inCart: false,
    imgSrc: casualT2,
    rating: 3.0,
  },
  {
    _id: uuid(),
    isFeatured: false,
    title: 'Mizuno sneakers',
    price: '13912',
    categoryName: 'fitness',
    inWishlist: false,
    inCart: false,
    imgSrc: fitnessT1,
    rating: 3.5,
  },
  {
    _id: uuid(),
    isFeatured: true,
    title: 'Reebok Hexaffect',
    price: '7999',
    categoryName: 'fitness',
    inWishlist: false,
    inCart: false,
    imgSrc: fitnessT2,
    rating: 3.0,
  },
  {
    _id: uuid(),
    isFeatured: true,
    title: 'Brroks Hyperion Max',
    price: '5999',
    categoryName: 'track',
    inWishlist: false,
    inCart: false,
    imgSrc: trackT1,
    rating: 3.5,
  },
  {
    _id: uuid(),
    isFeatured: false,
    title: 'Air Zoom Pegasus',
    price: '8996',
    categoryName: 'track',
    inWishlist: false,
    inCart: false,
    imgSrc: trackT2,
    rating: 4.5,
  },
  {
    _id: uuid(),
    isFeatured: true,
    title: 'New Balance Revlitye',
    price: '5890',
    categoryName: 'sports',
    inWishlist: false,
    inCart: false,
    imgSrc: sportsT1,
    rating: 4,
  },
  {
    _id: uuid(),
    isFeatured: false,
    title: 'Hummel Liga GK',
    price: '7199',
    categoryName: 'sports',
    inWishlist: false,
    inCart: false,
    imgSrc: sportsT2,
    rating: 3.5,
  },
]
